# Generated by Django 6.0 on 2026-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment_diagnosis_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
