# Generated by Django 6.0 on 2026-02-19 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='full_name',
            field=models.CharField(default='Unknown Doctor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('General Medicine', 'General Medicine'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics')], default='General Medicine', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
